HAI 1.4
CAN HAS STDIO?
I HAS A file ITZ I IZ STDIO'Z OPEN YR "append.dat" AN YR "a+" MKAY
I IZ STDIO'Z AGEIN YR file MKAY
I IZ STDIO'Z SCRIBBEL YR file AN YR "B" MKAY
I IZ STDIO'Z AGEIN YR file MKAY
VISIBLE I IZ STDIO'Z LUK YR file AN YR 2 MKAY
I IZ STDIO'Z CLOSE YR file MKAY
I HAS A readonly ITZ I IZ STDIO'Z OPEN YR "append.dat" AN YR "r" MKAY
I IZ STDIO'Z SCRIBBEL YR readonly AN YR "NOPE" MKAY
I IZ STDIO'Z DIAF YR readonly MKAY
O RLY?
  YA RLY
    VISIBLE "failed safely"
  NO WAI
    VISIBLE "unexpected success"
OIC
KTHXBYE
