BTW NOT: unary negation with truthiness auto-cast
HAI 1.2
  VISIBLE MAEK NOT WIN A NUMBR
  VISIBLE MAEK NOT FAIL A NUMBR
  VISIBLE MAEK NOT 0 A NUMBR
  VISIBLE MAEK NOT 42 A NUMBR
  VISIBLE MAEK NOT "" A NUMBR
  VISIBLE MAEK NOT "hai" A NUMBR
  VISIBLE MAEK NOT NOOB A NUMBR
KTHXBYE
