HAI 1.4
CAN HAS STDLIB?
I IZ STDLIB'Z MIX YR 42 MKAY
I HAS A first ITZ I IZ STDLIB'Z BLOW YR 1000 MKAY
I IZ STDLIB'Z MIX YR 42 MKAY
I HAS A second ITZ I IZ STDLIB'Z BLOW YR 1000 MKAY
VISIBLE first
VISIBLE second
KTHXBYE
