BTW SUM OF tests: NUMBR, NUMBAR, mixed types, nested expressions
HAI 1.2
  VISIBLE SUM OF 3 AN 4
  VISIBLE SUM OF 2.5 AN 1.25
  VISIBLE SUM OF 3 AN 4.0
  VISIBLE SUM OF PRODUKT OF 2 AN 3.5 AN DIFF OF 10 AN 4
KTHXBYE
