BTW PRODUKT OF tests: zero, negatives, mixed types
HAI 1.2
  VISIBLE PRODUKT OF 3 AN 4
  VISIBLE PRODUKT OF -3 AN 4
  VISIBLE PRODUKT OF 3 AN 0
  VISIBLE PRODUKT OF 2.5 AN 4
  VISIBLE PRODUKT OF -2.0 AN -3
  VISIBLE PRODUKT OF 2.0 AN 0
KTHXBYE
