BTW Test TYPE type
BTW Per spec: TYPE values are bare words (TROOF, NOOB, NUMBR, NUMBAR, YARN, TYPE)
BTW Per spec: may be cast to TROOF (all WIN except NOOB) or YARN

HAI 1.2
  BTW TYPE values as bare words
  I HAS A t1 ITZ NUMBR
  I HAS A t2 ITZ NUMBAR
  I HAS A t3 ITZ YARN
  I HAS A t4 ITZ TROOF
  I HAS A t5 ITZ NOOB
  I HAS A t6 ITZ TYPE

  BTW cast TYPE to YARN (prints type name)
  VISIBLE MAEK t1 A YARN
  VISIBLE MAEK t2 A YARN
  VISIBLE MAEK t3 A YARN
  VISIBLE MAEK t4 A YARN
  VISIBLE MAEK t5 A YARN
  VISIBLE MAEK t6 A YARN

  BTW cast TYPE to TROOF (all WIN except NOOB)
  VISIBLE MAEK NUMBR A TROOF
  VISIBLE MAEK NUMBAR A TROOF
  VISIBLE MAEK YARN A TROOF
  VISIBLE MAEK TROOF A TROOF
  VISIBLE MAEK NOOB A TROOF
  VISIBLE MAEK TYPE A TROOF

  BTW use TYPE in conditional
  NUMBR
  O RLY?
    YA RLY
      VISIBLE "NUMBR TYPE IS TRUTHY"
  OIC

  NOOB
  O RLY?
    YA RLY
      VISIBLE "NOOB TYPE IS TRUTHY"
    NO WAI
      VISIBLE "NOOB TYPE IS FALSY"
  OIC
KTHXBYE
