HAI 1.2
  BTW Test variables with names similar to keywords

  I HAS A SUMMER ITZ 100
  I HAS A NOTIFY ITZ "message"
  I HAS A TRUFFLE ITZ WIN
  I HAS A WINNER ITZ "you"
  I HAS A YARN_VALUE ITZ "string"

  VISIBLE SUMMER
  VISIBLE NOTIFY
  VISIBLE TRUFFLE
  VISIBLE WINNER
  VISIBLE YARN_VALUE

  I HAS A result ITZ SUM OF SUMMER AN 50
  VISIBLE result
KTHXBYE
