BTW DIFFRINT: inequality
HAI 1.2
  VISIBLE MAEK DIFFRINT 3 AN 4 A NUMBR
  VISIBLE MAEK DIFFRINT 3 AN 3 A NUMBR
  VISIBLE MAEK DIFFRINT "hai" AN "hai" A NUMBR
  VISIBLE MAEK DIFFRINT WIN AN FAIL A NUMBR
KTHXBYE
