HAI 1.2
HOW IZ I odd YR value
BOTH SAEM value AN 0
O RLY?
YA RLY
FOUND YR FAIL
OIC
FOUND YR I IZ even YR DIFF OF value AN 1 MKAY
IF U SAY SO
HOW IZ I even YR value
BOTH SAEM value AN 0
O RLY?
YA RLY
FOUND YR WIN
OIC
FOUND YR I IZ odd YR DIFF OF value AN 1 MKAY
IF U SAY SO
VISIBLE MAEK I IZ even YR 4 MKAY A NUMBR
KTHXBYE
