BTW ALL OF: infinite arity AND; MKAY terminator; MKAY may be omitted at EOL
HAI 1.2
  VISIBLE ALL OF WIN AN WIN AN WIN MKAY
  VISIBLE ALL OF WIN AN WIN AN FAIL MKAY
  VISIBLE ALL OF 1 AN "hai" AN 2 MKAY
  VISIBLE ALL OF WIN AN WIN AN WIN
  VISIBLE ALL OF WIN AN WIN AN FAIL
  VISIBLE ALL OF 1 2 3 MKAY
KTHXBYE
