BTW ANY OF: infinite arity OR; MKAY terminator; MKAY may be omitted at EOL
HAI 1.2
  VISIBLE ANY OF FAIL AN FAIL AN WIN MKAY
  VISIBLE ANY OF FAIL AN FAIL AN FAIL MKAY
  VISIBLE ANY OF "" AN 0 AN "x" MKAY
  VISIBLE ANY OF "" AN 0 AN NOOB MKAY
  VISIBLE ANY OF FAIL AN WIN
KTHXBYE
