BTW Boolean auto-cast: 0=FAIL, ""=FAIL, 42=WIN, "hai"=WIN, NOOB=FAIL
HAI 1.2
  VISIBLE MAEK 0 A TROOF
  VISIBLE MAEK "" A TROOF
  VISIBLE MAEK 42 A TROOF
  VISIBLE MAEK "hai" A TROOF
  I HAS A n
  VISIBLE MAEK n A TROOF
KTHXBYE
