BTW BOTH OF (AND): WIN/FAIL and auto-cast to TROOF from other types
HAI 1.2
  VISIBLE BOTH OF WIN AN WIN
  VISIBLE BOTH OF WIN AN FAIL
  VISIBLE BOTH OF 1 AN "hai"
  VISIBLE BOTH OF 0 AN "hai"
  VISIBLE BOTH OF 42 AN ""
  I HAS A x
  VISIBLE BOTH OF x AN WIN
  VISIBLE BOTH OF 0.0 AN WIN
KTHXBYE
