BTW EITHER OF (OR): truthiness across values
HAI 1.2
  VISIBLE EITHER OF WIN AN FAIL
  VISIBLE EITHER OF FAIL AN FAIL
  VISIBLE EITHER OF 0 AN "hai"
  VISIBLE EITHER OF "" AN 0
  VISIBLE EITHER OF NOOB AN FAIL
  VISIBLE EITHER OF NOOB AN "x"
KTHXBYE
