BTW WON OF (XOR): FAIL if same, WIN if different
HAI 1.2
  VISIBLE WON OF WIN AN WIN
  VISIBLE WON OF WIN AN FAIL
  VISIBLE WON OF 1 AN "hai"
  VISIBLE WON OF 0 AN ""
  VISIBLE WON OF 42 AN 0
KTHXBYE
