BTW Greater-than idiom: DIFFRINT x AN SMALLR OF x AN y (x > y)
HAI 1.2
  I HAS A x ITZ 5
  I HAS A y ITZ 3
  VISIBLE DIFFRINT x AN SMALLR OF x AN y
  x R 3
  y R 5
  VISIBLE DIFFRINT x AN SMALLR OF x AN y
  x R 5
  y R 5
  VISIBLE DIFFRINT x AN SMALLR OF x AN y
  x R 3.0
  y R 2
  VISIBLE DIFFRINT x AN SMALLR OF x AN y
  x R 3.0
  y R 3
  VISIBLE DIFFRINT x AN SMALLR OF x AN y
KTHXBYE
