BTW BOTH OF (AND): WIN/FAIL and auto-cast to TROOF from other types
HAI 1.2
  VISIBLE MAEK BOTH OF WIN AN WIN A NUMBR
  VISIBLE MAEK BOTH OF WIN AN FAIL A NUMBR
  VISIBLE MAEK BOTH OF 1 AN "hai" A NUMBR
  VISIBLE MAEK BOTH OF 0 AN "hai" A NUMBR
  VISIBLE MAEK BOTH OF 42 AN "" A NUMBR
  I HAS A x
  VISIBLE MAEK BOTH OF x AN WIN A NUMBR
  VISIBLE MAEK BOTH OF 0.0 AN WIN A NUMBR
KTHXBYE
