BTW MOD OF tests: edge cases including negatives and YARN casting
HAI 1.2
  VISIBLE MOD OF 7 AN 2
  VISIBLE MOD OF 7.0 AN 2
  VISIBLE MOD OF -7 AN 2
  VISIBLE MOD OF 7 AN -2
  VISIBLE MOD OF -7 AN -2
  VISIBLE MOD OF 0 AN 3
  VISIBLE MOD OF "10" AN "3"
  VISIBLE MOD OF "3.5" AN "2"
KTHXBYE
