BTW Nested math: deeply composed expressions
HAI 1.2
  VISIBLE SUM OF PRODUKT OF 2 AN DIFF OF 10 AN 5 AN QUOSHUNT OF 9 AN 3
  VISIBLE QUOSHUNT OF PRODUKT OF 2.5 AN SUM OF 1 AN 2 AN 2
  VISIBLE SUM OF SMALLR OF 10 AN 7 AN BIGGR OF 3 AN 4
KTHXBYE
