BTW Test line continuation with ... and … (ellipsis)
BTW Per spec: multiple lines combined into single command with ... or …

HAI 1.2
  BTW basic line continuation with ...
  VISIBLE "LINE" ...
    " CONTINUED"

  BTW line continuation with Unicode ellipsis …
  VISIBLE "UNICODE" …
    " ELLIPSIS"

  BTW multiple continuations chained
  VISIBLE ...
    "MULTI" ...
    " LINE" ...
    " CHAIN"

  BTW continuation in middle of keyword
  I HAS A ...
    longvar ITZ 42
  VISIBLE longvar

  BTW ... on its own line (empty line inclusion)
  VISIBLE "BEFORE" ...
    ...
    " AFTER"

  BTW continuation in expression
  I HAS A result ITZ SUM OF ...
    10 AN ...
    20
  VISIBLE result
KTHXBYE
