BTW WON OF (XOR): FAIL if same, WIN if different
HAI 1.2
  VISIBLE MAEK WON OF WIN AN WIN A NUMBR
  VISIBLE MAEK WON OF WIN AN FAIL A NUMBR
  VISIBLE MAEK WON OF 1 AN "hai" A NUMBR
  VISIBLE MAEK WON OF 0 AN "" A NUMBR
  VISIBLE MAEK WON OF 42 AN 0 A NUMBR
KTHXBYE
