<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lolcode.CodeAnalysis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lolcode.CodeAnalysis.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lolcode.Runtime\Lolcode.Runtime.csproj" />
  </ItemGroup>

</Project>
