HAI 1.2
I HAS A result1 ITZ SMOOSH "HAI" AN " " AN "WORLD" MKAY
VISIBLE result1
I HAS A num ITZ 42
I HAS A pi ITZ 3.14159
I HAS A result3 ITZ SMOOSH "NUM=" AN num AN ", PI=" AN pi MKAY
VISIBLE result3
VISIBLE SMOOSH "DIRECT " AN "VISIBLE" MKAY
KTHXBYE
