BTW BOTH SAEM has NO automatic casting: YARN "3" vs NUMBR 3
HAI 1.2
  VISIBLE MAEK BOTH SAEM "3" AN 3 A NUMBR
  VISIBLE MAEK BOTH SAEM "3.0" AN 3 A NUMBR
  VISIBLE MAEK DIFFRINT "3" AN 3 A NUMBR
KTHXBYE
