HAI 1.2
VISIBLE MAEK ANY OF FAIL AN FAIL AN WIN MKAY A NUMBR
VISIBLE MAEK ANY OF FAIL AN FAIL AN FAIL MKAY A NUMBR
VISIBLE MAEK ANY OF "" AN 0 AN "x" MKAY A NUMBR
VISIBLE MAEK ANY OF FAIL AN WIN MKAY A NUMBR
KTHXBYE
