BTW Boolean auto-cast: 0=FAIL, ""=FAIL, 42=WIN, "hai"=WIN, NOOB=FAIL
HAI 1.2
  VISIBLE MAEK MAEK 0 A TROOF A NUMBR
  VISIBLE MAEK MAEK "" A TROOF A NUMBR
  VISIBLE MAEK MAEK 42 A TROOF A NUMBR
  VISIBLE MAEK MAEK "hai" A TROOF A NUMBR
  I HAS A n
  VISIBLE MAEK MAEK n A TROOF A NUMBR
KTHXBYE
