BTW Type promotion: NUMBR+NUMBR=NUMBR; any NUMBAR promotes to NUMBAR
HAI 1.2
  VISIBLE SUM OF 1 AN 2
  VISIBLE DIFF OF 5 AN 3
  VISIBLE PRODUKT OF 2 AN 2
  VISIBLE QUOSHUNT OF 7 AN 2
  VISIBLE SUM OF 1.0 AN 2
  VISIBLE DIFF OF 5.0 AN 3
  VISIBLE PRODUKT OF 2 AN 2.5
  VISIBLE QUOSHUNT OF 7 AN 2.0
  VISIBLE SUM OF "3" AN "4.0"
KTHXBYE
