BTW NUMBAR comparison and NUMBR vs NUMBAR promotion
HAI 1.2
  VISIBLE MAEK BOTH SAEM 3 AN 3.0 A NUMBR
  VISIBLE MAEK BOTH SAEM 3.14 AN 3.140 A NUMBR
  VISIBLE MAEK DIFFRINT 3 AN 3.1 A NUMBR
  VISIBLE MAEK DIFFRINT 3.14 AN 3.13 A NUMBR
KTHXBYE
