BTW BOTH SAEM: equality for same type same value vs diff value
HAI 1.2
  VISIBLE MAEK BOTH SAEM 3 AN 3 A NUMBR
  VISIBLE MAEK BOTH SAEM 3 AN 4 A NUMBR
  VISIBLE MAEK BOTH SAEM "hai" AN "hai" A NUMBR
  VISIBLE MAEK BOTH SAEM "hai" AN "hai!" A NUMBR
  VISIBLE MAEK BOTH SAEM WIN AN WIN A NUMBR
  VISIBLE MAEK BOTH SAEM FAIL AN WIN A NUMBR
KTHXBYE
