BTW AN keyword optional between operands
HAI 1.2
  VISIBLE SUM OF 3 AN 4
  VISIBLE SUM OF 3 4
  VISIBLE DIFF OF 10 AN 3
  VISIBLE DIFF OF 10 3
  VISIBLE PRODUKT OF 2 AN 4
  VISIBLE PRODUKT OF 2 4
  VISIBLE QUOSHUNT OF 9 AN 3
  VISIBLE QUOSHUNT OF 9 3
  VISIBLE BIGGR OF 5 AN 5
  VISIBLE BIGGR OF 5 5
KTHXBYE
