BTW Test MAEK <expression> A NUMBAR from YARN, NUMBR, and TROOF
BTW Per spec: results print with two decimal places when cast to YARN

HAI 1.2
  BTW YARN to NUMBAR (integer)
  VISIBLE "YARN :"42:" AS NUMBAR:: " MAEK "42" A NUMBAR

  BTW YARN with decimal to NUMBAR
  VISIBLE "YARN :"3.14:" AS NUMBAR:: " MAEK "3.14" A NUMBAR

  BTW NUMBR to NUMBAR
  VISIBLE "NUMBR 7 AS NUMBAR:: " MAEK 7 A NUMBAR

  BTW TROOF to NUMBAR
  VISIBLE "WIN AS NUMBAR:: " MAEK WIN A NUMBAR
  VISIBLE "FAIL AS NUMBAR:: " MAEK FAIL A NUMBAR
KTHXBYE
