BTW Comprehensive casting matrix tests for LANGUAGE_SPEC Casting Rules Summary
BTW Per spec: verify each From -> To case with representative values

HAI 1.2
  BTW NUMBR -> YARN
  VISIBLE "NUMBR->YARN: " MAEK 42 A YARN

  BTW NUMBAR -> YARN (2 decimal places)
  I HAS A numbar ITZ 3.14159
  VISIBLE "NUMBAR->YARN: " MAEK numbar A YARN

  BTW TROOF -> YARN
  VISIBLE "TROOF WIN->YARN: " MAEK WIN A YARN
  VISIBLE "TROOF FAIL->YARN: " MAEK FAIL A YARN

  BTW YARN -> NUMBR
  VISIBLE "YARN \"123\"->NUMBR: " MAEK "123" A NUMBR
  VISIBLE "YARN \"4.56\"->NUMBR: " MAEK "4.56" A NUMBR

  BTW YARN -> NUMBAR
  VISIBLE "YARN \"4.56\"->NUMBAR: " MAEK "4.56" A NUMBAR

  BTW YARN -> TROOF
  VISIBLE "YARN \"\"->TROOF: " MAEK "" A TROOF
  VISIBLE "YARN \"LOL\"->TROOF: " MAEK "LOL" A TROOF

  BTW NUMBR -> TROOF
  VISIBLE "NUMBR 0->TROOF: " MAEK 0 A TROOF
  VISIBLE "NUMBR 5->TROOF: " MAEK 5 A TROOF

  BTW NUMBAR -> TROOF
  I HAS A zeroNumbar ITZ 0.0
  I HAS A nonzeroNumbar ITZ -1.5
  VISIBLE "NUMBAR 0.0->TROOF: " MAEK zeroNumbar A TROOF
  VISIBLE "NUMBAR -1.5->TROOF: " MAEK nonzeroNumbar A TROOF

  BTW TROOF -> NUMBR
  VISIBLE "TROOF WIN->NUMBR: " MAEK WIN A NUMBR
  VISIBLE "TROOF FAIL->NUMBR: " MAEK FAIL A NUMBR

  BTW TROOF -> NUMBAR
  VISIBLE "TROOF WIN->NUMBAR: " MAEK WIN A NUMBAR
  VISIBLE "TROOF FAIL->NUMBAR: " MAEK FAIL A NUMBAR

  BTW NOOB -> TROOF (implicit and explicit)
  I HAS A nothing ITZ NOOB
  VISIBLE "NOOB->TROOF (explicit): " MAEK nothing A TROOF
  nothing
  O RLY?
    YA RLY
      VISIBLE "NOOB->TROOF (implicit in O RLY?): WIN BRANCH"
    NO WAI
      VISIBLE "NOOB->TROOF (implicit in O RLY?): FAIL BRANCH"
  OIC

  BTW NOOB -> other (explicit)
  VISIBLE "NOOB->NUMBR: " MAEK nothing A NUMBR
  VISIBLE "NOOB->NUMBAR: " MAEK nothing A NUMBAR
  VISIBLE "NOOB->YARN: [" MAEK nothing A YARN "]"

  BTW TYPE -> TROOF
  I HAS A tnum ITZ NUMBR
  I HAS A tnoob ITZ NOOB
  VISIBLE "TYPE NUMBR->TROOF: " MAEK tnum A TROOF
  VISIBLE "TYPE NOOB->TROOF: " MAEK tnoob A TROOF

  BTW TYPE -> YARN
  VISIBLE "TYPE NUMBR->YARN: " MAEK tnum A YARN
  VISIBLE "TYPE NOOB->YARN: " MAEK tnoob A YARN
KTHXBYE
