BTW Test MAEK <expression> A YARN from NUMBR, NUMBAR, and TROOF
BTW Per spec: NUMBAR is truncated to 2 decimal places, TROOF prints WIN/FAIL

HAI 1.2
  BTW NUMBR to YARN
  VISIBLE "NUMBR 42 AS YARN:: " MAEK 42 A YARN

  BTW NUMBAR to YARN with 2 decimal digits
  VISIBLE "NUMBAR 3.14159 AS YARN:: " MAEK 3.14159 A YARN

  BTW TROOF to YARN
  VISIBLE "WIN AS YARN:: " MAEK WIN A YARN
  VISIBLE "FAIL AS YARN:: " MAEK FAIL A YARN
KTHXBYE
