BTW QUOSHUNT OF tests: integer vs float division
HAI 1.2
  VISIBLE QUOSHUNT OF 7 AN 2
  VISIBLE QUOSHUNT OF 7.0 AN 2
  VISIBLE QUOSHUNT OF 7 AN 2.0
  VISIBLE QUOSHUNT OF -7 AN 2
  VISIBLE QUOSHUNT OF 1 AN 2
  VISIBLE QUOSHUNT OF 1.0 AN 2
KTHXBYE
