HAI 1.4
CAN HAS STDLIB?
CAN HAS STRING?
I IZ STDLIB'Z MIX YR 99 MKAY
VISIBLE I IZ STDLIB'Z BLOW YR 0 MKAY
VISIBLE I IZ STRING'Z LEN YR "é" MKAY
VISIBLE "[" I IZ STRING'Z AT YR "HAI" AN YR -1 MKAY "]"
VISIBLE "[" I IZ STRING'Z AT YR "HAI" AN YR 3 MKAY "]"
KTHXBYE
